[package]
name = "simple-version"
version = "1.2.1"
edition = "2021"
authors = ["Park JiSoo <cherryjeesoo@gmail.com>"]
description = "The easiest way to manage versions in rust (I guess)"
license = "MIT"

[dependencies]
# No dependencies